### PR TITLE
alternate Calculus links

### LINKED ISSUE #17: Calculus 1A: Differentiation is no longer available at eDx
Calculus 1A: Differentiation is no longer available at eDx.
Please, provide equivalent alternative  for this course.

As far as I understand, copy of this course is available for free here: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.1x+2T2019/course/ although, **there's no way to get a certificate**.

### PR DESCRIPTION
**Pull request by spamegg1**
resolves #17

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
Good catch on the hours/week, that was definitely a slip up. I think that the number should actually be 9 hours. My reasoning:
Average course offers 3 credit hours. Recommendations for undergrads are that students spend 3x the credit hours on a course (though surveys suggest the actual time spent is 2x). I assume that the text will have the same time commitment as a semester college course. Hence 9 hours per week for 15 weeks.

**Comment by spamegg1** [comment]
@waciumawanjohi OK to merge?

**Comment by waciumawanjohi** [comment]
Looks good. One quick question, is there meant to be a second alt on the integration course? There's an alt1 but no alt2.

**Comment by spamegg1** [comment]
I got the alternate links from the Computer Science curriculum. Calculus 1 had two links, whereas the others only had one. So now Calc 1 has 3 links, and the others have 2 each.

I guess right now it looks kind of... uneven.

I guess I could go look for one... There is: edX, OLL, and OCW.

**Comment by spamegg1** [comment]
I think I understand the issue now. The older OCW versions have a different separation of Calculus, into TWO courses (Single and Multi variable). The newer edX/OLL versions instead split single variable calculus into THREE courses.

The older OCW Single variable course actually covers roughly the equivalent of Calculus 1A and 1B, even a portion of 1C (infinite series).

Maybe it's better to remove the alt2 link then? I'll do that.

**Comment by waciumawanjohi** [comment]
Good to go!

**Pull request merged**
