### PR TITLE
Improvements to Math Curriculum: typo correction, curriculum alignment, description accuracy, and linking of prerequisites

### PR DESCRIPTION
**Pull request by anantav51**
The original description for this course may have led to confusion about the nature of Analysis. Analysis is a branch of mathematics that deals with the study of limits, properties of functions, and the infinite. While it does make use of formal proof, it is not to be confused with metamathematics which is the study of mathematical reasoning and foundations.

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
Given an approval from a previous contributor to the Math curriculum, I'll merge this change in. If no contributor approves within 1 month, I'll close the PR. I recommend engaging contributors in our discord channel: https://discord.gg/9mgKwXEvb3

**Comment by anantav51** [comment]
I spotted a typo in the prerequisites column of Topology Without Tears, so I figured I might as well make more changes to bring it closer in alignment with the Computer Science curriculum by organizing each section and subsection under a "Curriculum" heading and linking them accordingly. Additionally, I also linked all courses that list high school math as a prerequisite to the FAQ section, since that information isn't included in the "Curriculum" section as per the Computer Science curriculum.

**Comment by aayushsinha0706** [comment]
Please also add this in topology without tears section 

Knowledge of axiomatic branch of mathematics such as Introduction to Abstract Algebra

**Comment by waciumawanjohi** [comment]
@anantav51 It seems like you are still working on this pull request. Can you [convert this to a draft PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) until you are done and [ready for a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review)?

**Comment by anantav51** [comment]
> @anantav51 It seems like you are still working on this pull request. Can you [convert this to a draft PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) until you are done and [ready for a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review)?

I think that's it!

**Comment by aayushsinha0706** [comment]
Approve the changes 👍🏼

**Pull request merged**
